# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=300)),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('closed', models.DateTimeField(verbose_name='date finished')),
            ],
        ),
    ]
