# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 00:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('website', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('issue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.Issue')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='assignee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='website.Contributor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='issuer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issuer', to='website.Contributor'),
            preserve_default=False,
        ),
    ]
