# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160303_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Contributor'),
            preserve_default=False,
        ),
    ]
