# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160303_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'Hi')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Closed')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
