# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_commit_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='contributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Contributor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Repository'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
