# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20160304_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='issue',
        ),
        migrations.AddField(
            model_name='tag',
            name='issue',
            field=models.ManyToManyField(to='website.Issue'),
        ),
    ]
