# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20160308_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='issue',
            new_name='issues',
        ),
        migrations.AddField(
            model_name='contributor',
            name='github_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributor',
            name='img_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='contributors',
            field=models.ManyToManyField(to='website.Contributor'),
        ),
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='github_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
