# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20160308_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='issues',
        ),
        migrations.AddField(
            model_name='issue',
            name='commit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Commit'),
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(to='website.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='tag',
            name='font_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='website.Contributor'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date finished'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('0', 'New'), ('1', 'In Progress'), ('2', 'Closed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
