# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-18 10:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20160310_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 10, 19, 13, 710870, tzinfo=utc), verbose_name='commented on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='github_url',
            field=models.CharField(default='http://github.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='hash',
            field=models.CharField(default='someprettyhandsomehash', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='website.Repository'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.Contributor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.Issue'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='website.Contributor'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='website.Repository'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='img_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues_assigned', to='website.Contributor'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='commit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='website.Commit'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_author', to='website.Contributor'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='issues', to='website.Tag'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='contributors',
            field=models.ManyToManyField(related_name='contributed_repositories', to='website.Contributor'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_repositories', to='website.Contributor'),
        ),
    ]
