# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-28 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20160418_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='repository',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Repository'),
        ),
    ]
